name: CI

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Run a one line script
      shell: echo Hello World!
      
    - name: Run make commande
      shell: make hello
